sonar.projectKey=ep3-productos_EntregaEvaluacion32
sonar.organization=ep3-productoss

sonar.host.url=https://sonarcloud.io
sonar.java.binaries=target/classes
sonar.sources=src/main/java
sonar.tests=src/test/java
